### ISSUE TITLE
Doesn't support meat!!!!!!!!!!

### ISSUE THREAD

**Issue by Bongs237** [Bongs237/redesigned-octo-broccoli#1]
I tried using the octo broccoli but it didn't work. I realized that I was cooking meat with it and then it exploded. Maybe try fixing line 195 where it says:
`Meat.stuff = false`
and change it to:
`Meat.stuff = true`
Thanks,
Bongs
👍

**Comment by Bongs237** [comment]
ok

**Comment by Bongs237** [comment]
Fixed

**Comment by KwiatekMiki** [comment]
nO
